services:
  # PostgreSQL Database
  db:
    image: postgres:15
    container_name: minivault_db
    environment:
      POSTGRES_DB: minivaultdb
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: db123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d minivaultdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI 
  app:
    build: .
    container_name: minivault_app
    environment:
      - DATABASE_URL=postgresql+psycopg2://dbuser:db123456@db:5432/minivaultdb
      - STORAGE_LOCATION=/app/data
      - FILE_ENCRYPTION_KEY=mjdxE3f3umYSxFxxrAYbM8iWeJHxHYsX8JkpSOkBGcY=
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: