"""add current_storage in User table

Revision ID: 3253f7707977
Revises: ea6f6e2bc056
Create Date: 2025-07-14 15:46:50.649286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3253f7707977'
down_revision: Union[str, Sequence[str], None] = 'ea6f6e2bc056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('current_storage', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_storage')
    # ### end Alembic commands ###
