"""add shared table

Revision ID: ea6f6e2bc056
Revises: 7281b04c124f
Create Date: 2025-07-13 19:48:46.417748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ea6f6e2bc056'
down_revision: Union[str, Sequence[str], None] = '7281b04c124f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shared_files', sa.Column('file_id', sa.String(), nullable=True))
    op.add_column('shared_files', sa.Column('shared_user_id', sa.String(), nullable=True))
    op.add_column('shared_files', sa.Column('shared_at', sa.DateTime(), nullable=True))
    op.add_column('shared_files', sa.Column('permission', sa.String(), nullable=True))
    op.drop_constraint(op.f('shared_files_owner_user_id_fkey'), 'shared_files', type_='foreignkey')
    op.create_foreign_key(None, 'shared_files', 'users', ['shared_user_id'], ['id'])
    op.create_foreign_key(None, 'shared_files', 'files', ['file_id'], ['id'])
    op.drop_column('shared_files', 'created_at')
    op.drop_column('shared_files', 'location')
    op.drop_column('shared_files', 'file_name')
    op.drop_column('shared_files', 'checksum')
    op.drop_column('shared_files', 'owner_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shared_files', sa.Column('owner_user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('shared_files', sa.Column('checksum', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('shared_files', sa.Column('file_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('shared_files', sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('shared_files', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'shared_files', type_='foreignkey')
    op.drop_constraint(None, 'shared_files', type_='foreignkey')
    op.create_foreign_key(op.f('shared_files_owner_user_id_fkey'), 'shared_files', 'users', ['owner_user_id'], ['id'])
    op.drop_column('shared_files', 'permission')
    op.drop_column('shared_files', 'shared_at')
    op.drop_column('shared_files', 'shared_user_id')
    op.drop_column('shared_files', 'file_id')
    # ### end Alembic commands ###
